FROM mcr.microsoft.com/openjdk/jdk:21-ubuntu
# Accept build arguments
ARG JWT_SECRET
ARG MONGODB_CONNECTION_STRING
ARG AZURE_STORAGE_ACCOUNT_CONNECTION_STRING
ARG AZURE_COMMUNICATION_SERVICE_CONNECTION_STRING
ARG APP_BASE_URL

# Set as environment variables
ENV JWT_SECRET=${JWT_SECRET}
ENV MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
ENV AZURE_STORAGE_ACCOUNT_CONNECTION_STRING=${AZURE_STORAGE_ACCOUNT_CONNECTION_STRING}
ENV AZURE_COMMUNICATION_SERVICE_CONNECTION_STRING=${AZURE_COMMUNICATION_SERVICE_CONNECTION_STRING}
ENV APP_BASE_URL=${APP_BASE_URL}

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]