app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

spring:
  profiles:
    active: dev
  application:
    name: "apigateway"
  security:
    require-ssl: false # Set to true in production
  doc:
    api-docs:
      path: /api-docs       # default is /v3/api-docs
    swagger-ui:
      path: /swagger-ui     # default is /swagger-ui
      operationsSorter: alpha
      tagsSorter: alpha
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_CONNECTION_STRING}
      # Increase timeouts
      connect-timeout: 30000
      socket-timeout: 60000

registration:
  token:
    expiration: 86400000 # 1 day in milliseconds
    max-attempts: 5
    resend-interval: 300000 # 5 minutes in milliseconds

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  verification:
    expiration: 86400000 # 1 day in milliseconds
  refresh:
    expiration: 604800000

server:
  port: 8080

logging:
  level:
    com.muditsahni: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized


azure:
  storage:
    connection-string: ${AZURE_STORAGE_ACCOUNT_CONNECTION_STRING}
    container-name: uploads
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
    account-key: ${AZURE_STORAGE_ACCOUNT_KEY_VALUE}

  eventgrid:
    endpoint: ${AZURE_EVENTGRID_ENDPOINT}
    key: ${AZURE_EVENTGRID_KEY}

  communication:
    email:
      connection-string: ${AZURE_COMMUNICATION_SERVICE_CONNECTION_STRING}
      sender-address: DoNotReply@c6f6e1fd-0fd5-498c-a50b-073682247c9e.azurecomm.net