spring:

  profiles:
    active: dev
  application:
    name: "apigateway"
  security:
    require-ssl: false # Set to true in production
  doc:
    api-docs:
      path: /api-docs       # default is /v3/api-docs
    swagger-ui:
      path: /swagger-ui     # default is /swagger-ui
      operationsSorter: alpha
      tagsSorter: alpha
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_CONNECTION_STRING}
      # Increase timeouts
      connect-timeout: 30000
      socket-timeout: 60000

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  refresh:
    expiration: 604800000

server:
  port: 8080

logging:
  level:
    com.muditsahni: DEBUG
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
