spring:

  profiles:
    active: dev  # default to dev
  application:
    name: "apigateway"
  security:
    require-ssl: false # Set to true in production
  doc:
    api-docs:
      path: /api-docs       # default is /v3/api-docs
    swagger-ui:
      path: /swagger-ui     # default is /swagger-ui
      operationsSorter: alpha
      tagsSorter: alpha
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://muditsahni:<SECRET>@invoicesdb00001.global.mongocluster.cosmos.azure.com/invoices?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      # Increase timeouts
      connect-timeout: 30000  # 30 seconds
      socket-timeout: 60000   # 60 seconds

jwt:
  secret: <ADD_SECRET>
  expiration: 86400000    # 24 hours
  refresh:
    expiration: 604800000 # 7 days

server:
  port: 8080

logging:
  level:
    com.muditsahni: DEBUG
    org.springframework.security: INFO # Change to DEBUG for troubleshooting
    org.springframework.data.mongodb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
